services:
  session:
    build:
      dockerfile: Dockerfile
      context: ./.docker
    environment:
      - SERVICE_NODE_IP_ADDRESS=${SERVICE_NODE_IP_ADDRESS:?}
      - L2_PROVIDER=${L2_PROVIDER:?}
      - LMQ_PORT=${LMQ_PORT:?}
      - STORAGE_SERVER_PORT=${STORAGE_SERVER_PORT:?}
      - P2P_PORT=${P2P_PORT:?}
      - QUORUMNET_PORT=${QUORUMNET_PORT:?}
    restart: unless-stopped
    tty: true
    ports:
      - "${LMQ_PORT:?}:${LMQ_PORT:?}/tcp"
      - "${LMQ_PORT:?}:${LMQ_PORT:?}/udp"
      - "${P2P_PORT:?}:${P2P_PORT:?}/tcp"
      - "${QUORUMNET_PORT:?}:${QUORUMNET_PORT:?}/tcp"
    privileged: true
    stdin_open: true
    networks:
      session:
        ipv4_address: 10.0.5.2
    volumes:
      - ./oxen-data:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  session-storage:
    build:
      dockerfile: Dockerfile-storage-server
      context: ./.docker
    environment:
      - LMQ_PORT=${LMQ_PORT:?}
      - STORAGE_SERVER_PORT=${STORAGE_SERVER_PORT:?}
    restart: unless-stopped
    ports:
      - "${STORAGE_SERVER_PORT:?}:${STORAGE_SERVER_PORT:?}/tcp"
    privileged: true
    networks:
      session:
        ipv4_address: 10.0.5.3
    volumes:
      - ./oxen-data:/var/lib/oxen
      - ./storage-data:/var/lib/oxen/storage
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  session-lokinet:
    build:
      dockerfile: Dockerfile-lokinet
      context: ./.docker
    environment:
      - SERVICE_NODE_IP_ADDRESS=${SERVICE_NODE_IP_ADDRESS:?}
      - LOKINET_PORT=${LOKINET_PORT:?}
    privileged: true
    restart: unless-stopped
    ports:
      - "${LOKINET_PORT:?}:${LOKINET_PORT:?}/udp"
    networks:
      session:
        ipv4_address: 10.0.5.4
    volumes:
      - ./oxen-data:/var/lib/oxen
      - ./lokinet-data:/var/lib/lokinet/router
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

networks:
  session:
    ipam:
      config:
        - subnet: 10.0.5.0/24