services:
  session:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./oxen:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535