services:
  session:
    build:
      dockerfile: Dockerfile
      context: ./.docker
    restart: unless-stopped
    tty: true
    privileged: true
    stdin_open: true
    volumes:
      - ./oxen:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  session-storage:
    build:
      dockerfile: Dockerfile-storage-server
      context: ./.docker
    restart: unless-stopped
    privileged: true
    volumes:
      - ./oxen:/var/lib/oxen
  session-lokinet:
    build:
      dockerfile: Dockerfile-lokinet
      context: ./.docker
    privileged: true
    restart: unless-stopped
    volumes:
      - ./oxen:/var/lib/oxen