services:
  session:
    build:
      dockerfile: Dockerfile
      context: ./.docker
    restart: unless-stopped
    tty: true
    ports:
      - "6969"
    privileged: true
    stdin_open: true
    networks:
      session:
        ipv4_address: 10.0.5.2
    volumes:
      - ./oxen:/var/lib/oxen
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  session-storage:
    build:
      dockerfile: Dockerfile-storage-server
      context: ./.docker
    restart: unless-stopped
    privileged: true
    networks:
      session:
        ipv4_address: 10.0.5.3
    volumes:
      - ./oxen:/var/lib/oxen
      - ./storage-data:/var/lib/oxen/storage
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  session-lokinet:
    build:
      dockerfile: Dockerfile-lokinet
      context: ./.docker
    privileged: true
    restart: unless-stopped
    networks:
      session:
        ipv4_address: 10.0.5.4
    volumes:
      - ./oxen:/var/lib/oxen
      - ./lokinet-data:/var/lib/lokinet/router
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

networks:
  session:
    ipam:
      config:
        - subnet: 10.0.5.0/24