FROM ubuntu:24.04

RUN apt update

RUN apt install -y curl adduser screen gettext unzip jq

RUN curl -so /etc/apt/trusted.gpg.d/oxen.gpg https://deb.oxen.io/pub.gpg

RUN echo "deb https://deb.oxen.io noble main" | tee /etc/apt/sources.list.d/oxen.list

RUN apt update

RUN apt install -y lokinet

COPY etc/loki/lokinet-router.ini /etc/loki/lokinet-router_template.ini

COPY entrypoint.sh /

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["lokinet", "-r", "/etc/loki/lokinet-router.ini"]